### ISSUE TITLE
no MidasDetector export

### ISSUE THREAD

**Issue by junjiexv** [patrickvonplaten/controlnet_aux#11]
i want to use MidasDetector, but it failed:

from controlnet_aux import OpenposeDetector, MLSDdetector, MidasDetector, CannyDetector, HEDdetector
ImportError: cannot import name 'MidasDetector' from 'controlnet_aux'

**Comment by jinwonkim93** [comment]
@junjiexv 
try installing by 
pip uninstall controlnet_aux
pip install git+https://github.com/patrickvonplaten/controlnet_aux.git

**Comment by junjiexv** [comment]
thinks, it works!
