### ISSUE TITLE
mismatch in tensor size for MidasDetector

### ISSUE THREAD

**Issue by arisha07** [patrickvonplaten/controlnet_aux#17]
I am new to using this package, so not sure if I am doing the right thing:
Here is my code - (Running on CPU)

```
from controlnet_aux import MidasDetector
from PIL import Image

depth_estimator = MidasDetector.from_pretrained("lllyasviel/ControlNet")

image_file = "<loaction.png>"
img = Image.open(image_file)
depth_map, i = depth_estimator(img)
```

After running I get a runtime error - 
RuntimeError: The size of tensor a (1505) must match the size of tensor b (1473) at non-singleton dimension 1

Please let me know if there is something that I am missing here. Thank you !

**Comment by jinwonkim93** [comment]
Have you tried resizing img? check https://github.com/patrickvonplaten/controlnet_aux/issues/2

**Comment by arisha07** [comment]
Thanks that worked !
