### ISSUE TITLE
Can't load CannyDetector in Jarvis

### ISSUE THREAD

**Issue by panchromatic242** [patrickvonplaten/controlnet_aux#19]
I will say up front that I am not a coder, so I am susceptible to probably a thousand horrifyingly obvious mistakes!  I'm sure those will include etiquette breaches for which I apologize in advance.

With that said, I'm managed to get Jarvis installed and resolved a ton of dependencies along the way. But I'm stuck on this one.

```
(jarvis) root@[...]:~/JARVIS/server# python models_server.py --config config.yaml
Traceback (most recent call last):
  File "models_server.py", line 29, in <module>
    from controlnet_aux import OpenposeDetector, MLSDdetector, HEDdetector, CannyDetector, MidasDetector
ImportError: cannot import name 'CannyDetector' from 'controlnet_aux' (/root/anaconda3/envs/jarvis/lib/python3.8/site-packages/controlnet_aux/__init__.py)
(jarvis) root@[...]:~/JARVIS/server# grep -R CannyDetector /root/anaconda3/envs/jarvis/lib/python3.8/site-packages/controlnet_aux/*
(jarvis) root@[...]:~/JARVIS/server#
```

Based on ChatGPT's feedback it looks like the CannyDetector module is never defined in controlnet_aux.  Is this accurate?  

Appreciate your patience if this is something I've screwed up and could/should fix on my own!

**Comment by panchromatic242** [comment]
Oops! Looks like this is addressed in a pending PR. :) I'll check back again soon.

**Comment by LesenlyMu** [comment]
cd to comfyui_controlnet_aux floder,  and then,  "git pull"
