### ISSUE TITLE
Detector differences with ControlNet 1.1 implementation

### ISSUE THREAD

**Issue by pdoane** [patrickvonplaten/controlnet_aux#23]
Thanks for making the 0.0.3 so quickly - up and running on 1.1 models!

I noticed a few things during integration:
- Do you want to continue to support ControlNet 1.0?  If so maybe MidasDetector should continue to return the normal map?  Otherwise, the code that computes the normal map can be removed.
- Do you want additional detectors?  I noticed ZoeDetector, OneformerCOCODetector, OneformerADE20kDetector, and UniformerDetector.  Maybe more.
- Should I handle 'Safe Mode' for HED/PIDI detectors or should that be added as a parameter?

Happy to help on any of these, but wanted to coordinate first.

**Comment by patrickvonplaten** [comment]
Great questions! 

1) Regarding MiDAS, sorry I removed the normal map a bit in a rush to align the API (see README.md) - what is the normal map used for? Would one ever need to use both the normal map and the depth map? Happy to add it back with a flag maybe so that by default is returns just a PIL Image

2) Sure happy to review PRs!

3) That'd be great for PIDI I already added a `safe` flag - haven't done it for HED yet

**Comment by pdoane** [comment]
From my limited understanding: For ControlNet 1.0, the MiDAS depth and normal map are used for their respective pipelines.  In 1.1, the normal map pipeline now needs more accurate normal maps that comes from the NormalBae detector.  So, the MiDAS normal map output is only interesting for continuing to support ControlNet 1.0.  As to using both normal and depth map, might be interesting for MultiControlNet.

I'll work on some PRs for all of these.

There's also reference to Depth_Leres in the documentation but not the implementation.  I've seen Leres mentioned in other ControlNet implementations so that might be interesting to compare against Midas/Zoe.

**Comment by ethansmith2000** [comment]
came here to make an issue on the same matter, thank you for all you do @patrickvonplaten !!

**Comment by pdoane** [comment]
I'm going to close this one out - we've addressed most of the original issue.  Maybe someone else is interested in the segmentation detectors.
