### ISSUE TITLE
LICENSE for this package

### ISSUE THREAD

**Issue by lanking520** [patrickvonplaten/controlnet_aux#35]
Hi there, would like to check what is the LICENSE attritibution to this project. For production usage, we could not use any unlicensed project on this use case.

**Comment by lanking520** [comment]
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Ah yeah sorry! Since most of the code originates from https://github.com/lllyasviel/ControlNet I think we can freely pick a license here, so let's just use MIT no?

**Comment by patrickvonplaten** [comment]
https://github.com/patrickvonplaten/controlnet_aux/commit/f31dbd95cf7426164d0d0f88fe7339afcfbcb668

**Comment by lanking520** [comment]
Thanks! That's helpful! Please include that next time in your pypi distribution if possible.
