### ISSUE TITLE
Installing from pipy and can't find mediapipe

### ISSUE THREAD

**Issue by dkackman** [patrickvonplaten/controlnet_aux#44]
On windows,m installing package from pipy. Installs fine but at runtime it fails with 

```
Exception has occurred: ImportError
The module 'mediapipe' is not installed. Please install it using the command: pip install 'mediapipe'
ModuleNotFoundError: No module named 'mediapipe'
```

`pip install mediapipe` does not find a package to install.

```
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
```

Not sure if this a windows thing or not. I am **not** using the mediapipe annotator.

**Comment by Ambrosiussen** [comment]
Odd... Certainly exists! https://pypi.org/project/mediapipe/

**Comment by dkackman** [comment]
> Odd... Certainly exists! https://pypi.org/project/mediapipe/

indeed. also... works fine on Ubuntu. I'll try it on another windows machine

**Comment by dkackman** [comment]
documented issue in media pipe - closing
