### ISSUE TITLE
Add a to_device() method for each model

### ISSUE THREAD

**Issue by ChristiaensBert** [patrickvonplaten/controlnet_aux#51]
Currently, each ML model has a different way of putting the network on CUDA (or other devices).
Some model classes have multiple submodels, so you can't just call model.cuda(), such as the HedDetector and the Openpose detector which e.g. has 

```python
self.body_estimation = body_estimation
self.hand_estimation = hand_estimation
self.face_estimation = face_estimation
```

We should add a to_device(device: str) method for each of the models that gives a consistent interface for putting all needed models on a device.

```python
class OpenposeDetector:
    def __init__(...):
        pass

    def to_device(self, device: str) -> None:
        self.body_estimation.to(device)
        self.hand_estimation.to(device)
        self.face_estimation.to(device)
```

Maybe there are other methods that we can standardize between the different processor classes, in order to have a general interface that can be reused and called from the Processor class

**Comment by pdoane** [comment]
I did this in #48, although I didn't put an empty method for annotators that didn't need it.

**Comment by ChristiaensBert** [comment]
Oh awesome, I missed it. Thanks for implementing these features :D
