### ISSUE TITLE
why remove openpose's handDetect?

### ISSUE THREAD

**Issue by goodspb** [patrickvonplaten/controlnet_aux#6]

**Comment by patrickvonplaten** [comment]
Ah I think it's because it didn't really work no? Tbh, I just wanted to have a quick solution working so I removed it - happy to review a PR that adds it again if it works :-)

**Comment by goodspb** [comment]
thanks. after some experiments. I think without hand detect is work just the same as what I do in WebUI which uses both hand and body detection.
