### ISSUE TITLE
Release not updated

### ISSUE THREAD

**Issue by pietrobolcato** [patrickvonplaten/controlnet_aux#60]
Hey there! Thanks for the great work!

The latest release we install from pip is not updated, and for example doesn't support arguments shown in the example code in readme, like `to_pil`, or processors like `scribble_hed`. Is it possible to create a new release with these?

Thanks a lot!

**Comment by patrickvonplaten** [comment]
Hey @pietrobolcato,

I'll try to do one end of this week

**Comment by patrickvonplaten** [comment]
Here we go: https://pypi.org/project/controlnet-aux/0.0.6/

**Comment by pietrobolcato** [comment]
Thank you so much! :)
